# Generated by Django 5.2.3 on 2026-04-01 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.organization')),
            ],
            options={
                'db_table': 'items',
                'indexes': [models.Index(fields=['organization'], name='items_organiz_e806cb_idx'), models.Index(fields=['created_by'], name='items_created_705f7e_idx'), models.Index(fields=['created_at'], name='items_created_78d389_idx'), models.Index(fields=['organization', 'created_by'], name='items_organiz_2c18ff_idx')],
            },
        ),
    ]
